# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originating_url', models.CharField(help_text='The originating URL that triggered a 404 error or is manually entered.', max_length=255, unique=True)),
                ('redirect_to_url', models.CharField(blank=True, help_text='Optional. Specify the URL to which the originating URL should redirect. This should be an absolute or root-relative URL.', max_length=255, null=True)),
                ('redirect_type', models.CharField(choices=[(b'301', b'301 - Permanent'), (b'302', b'302 - Temporary')], default=b'301', max_length=10)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='site')),
            ],
            options={
                'ordering': ('originating_url',),
                'verbose_name': 'redirect',
                'verbose_name_plural': 'redirects',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referer_url', models.CharField(help_text='The URL of the previous page that redirected to this url that generated the 404 error.', max_length=1000)),
                ('hits', models.PositiveIntegerField(default=0, help_text='The number of times the originating URL has been hit.')),
                ('last_hit', models.DateTimeField(blank=True, help_text='The last time the originating URL was hit.', null=True)),
                ('redirect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='redirector.Redirect')),
            ],
            options={
                'ordering': ('-hits',),
            },
        ),
    ]
